"""Add error_message, timestamp, completed_at to PluginExecution

Revision ID: 2d69244356e1
Revises: f4fa5b30e239
Create Date: 2025-04-29 16:52:49.411162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d69244356e1'
down_revision: Union[str, None] = 'f4fa5b30e239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_executions', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('plugin_executions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'error_message')
    op.drop_column('plugin_executions', 'completed_at')
    op.drop_column('plugin_executions', 'error_message')
    # ### end Alembic commands ###
