"""Fix chat title and add timestamp to chat message

Revision ID: 506e04309528
Revises: afda61306ff8
Create Date: 2025-05-10 00:16:00.836596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506e04309528'
down_revision: Union[str, None] = 'afda61306ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('chat_messages', 'created_at')
    op.add_column('chats', sa.Column('title', sa.String(), nullable=False))
    op.drop_index('ix_chats_name', table_name='chats')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.create_index('ix_chats_name', 'chats', ['name'], unique=False)
    op.drop_column('chats', 'title')
    op.add_column('chat_messages', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('chat_messages', 'timestamp')
    # ### end Alembic commands ###
