"""Add understanding to project

Revision ID: 6b9b4325395a
Revises: ff12ad0ec871
Create Date: 2025-05-10 04:04:08.022040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9b4325395a'
down_revision: Union[str, None] = 'ff12ad0ec871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('understanding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'understanding')
    # ### end Alembic commands ###
