"""Fix ChatMessage to use created_at

Revision ID: ff12ad0ec871
Revises: 506e04309528
Create Date: 2025-05-10 00:19:20.054997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff12ad0ec871'
down_revision: Union[str, None] = '506e04309528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('chat_messages', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.drop_column('chat_messages', 'created_at')
    # ### end Alembic commands ###
